//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Project1_top(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////

	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
	wire [7:0] s;



//=======================================================
//  Structural coding
//=======================================================
	SevenSeg testHex0(s[3:0],HEX0[6:0]);	
	Add testAdd(SW[7:4],SW[3:0],0,s[3:0],HEX0[7],LEDR[7]);
	


endmodule
